version: "3.8"

services:
#  mysql:
#    image: mysql:8.0
#    container_name: mysql-3309
#    environment:
#      MYSQL_ROOT_PASSWORD: kien2005
#    ports:
#      - "3309:3306"
#    networks:
#      - mysql-network
  ecommerce:
    build:
      context: .
      dockerfile: Dockerfile
    image: shop-app:3.0
    container_name: eCommerce
    ports:
      - "8081:8080"
    networks:
      - network

networks:
  network:
    driver: bridge
