version: '3.8'

services:
  app:
    image: shop-app
    container_name: ecommerce
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shopapp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: kien2005

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: kien2005
      MYSQL_DATABASE: shopapp
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
