server:
  port:
    8080
spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://192.168.13.1:3306/shopapp}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:kien2005}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
        client:
          registration:
            github:
              client-id: Ov23li2eZwOx10LGCSxF
              client-secret: e1cd2cc0bb34b5cb976ad5ee353fe340965fb8ad
            google:
              client-id: 883269268303-qk6qn8gfafdbuj369u7usosj3h7a3n65.apps.googleusercontent.com
              client-secret: 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
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        mime:
          charset: UTF-8
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enabled: true
            required: true
    verify:
      host: ${HOST}
api:
  prefix: /api/v1
jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey: iR/y3oZJM5IjK1n929d90COUtz9c52eThZzlcqVRhqQ=