server:
  port:
    8081
spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3308/shopapp}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:kien2005}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
        client:
          registration:
            github:
              client-id: ${GITHUB_CLIENT_ID}
              client-secret: ${GITHUB_CLIENT_SECRET}
            google:
              client-id: ${GOOGLE_CLIENT_ID}
              client-secret: ${GOOGLE_CLIENT_SECRET}
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        mime:
          charset: UTF-8
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enabled: true
            required: true
    verify:
      host: ${HOST}
api:
  prefix: /api/v1
jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey: iR/y3oZJM5IjK1n929d90COUtz9c52eThZzlcqVRhqQ=

payment:
  vnPay:
    url: ${PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
    tmnCode: ${TMN_CODE:PA213E9L}
    secretKey: ${SECRET_KEY:EQB0S4UKU4KDN1QWZA940APF2BTZ7FTV}
    returnUrl: ${RETURN_URL:${api.prefix}/payment/vn-pay-callback}
    version: ${VERSION:2.1.0}
    command: ${COMMAND:pay}
    orderType: ${ORDER_TYPE:other}
