name: Java CI with Maven
env:
    SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/shoppapp
    SPRING_DATASOURCE_USERNAME: root
    SPRING_DATASOURCE_PASSWORD: kien2005
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: kien2005
          MYSQL_DATABASE: shoppapp
        ports:
          - 3307:3306
        options:
          --health-cmd="mysqladmin ping -h localhost -u root -pkien2005" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and test with maven
        run: mvn --batch-mode package
